# Generated by Django 5.1.6 on 2025-03-29 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_remove_customer_email_remove_customer_password_and_more'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_title', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('business_address', models.TextField()),
                ('subscription_status', models.BooleanField(default=False)),
                ('subscription_date', models.DateField(blank=True, null=True)),
                ('products', models.ManyToManyField(related_name='sellers', to='products.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Merchant',
        ),
    ]
