# Generated by Django 5.1.6 on 2025-03-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_remove_customer_email_remove_customer_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
